# Prediction Assignment Writeup
### Mark Anderson
### Coursera Practical Machine Learning (predmachlearn-013)

```{r echo=TRUE}
train_data_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
if (!file.exists("pml-training.csv")) {
  download.file(train_data_url, destfile='pml-training.csv', method='curl')
}
pml_train <- read.csv("pml-training.csv", na.strings = c("NA",""))
dim(pml_train)
```

```{r echo=TRUE}
testing_data_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
if (!file.exists("pml-testing.csv")) {
  download.file(testing_data_url, destfile='pml-testing.csv', method='curl')
}
pml_test <- read.csv("pml-testing.csv", na.strings = c("NA",""))
dim(pml_test)
```

Tidy up data
```{r echo=TRUE}
tidy_train <- pml_train[!grepl("yes",pml_train$new_window),]
artifacts <- c(1:7)
cn_kurtosis  <- grep("^kurtosis_", colnames(tidy_train))
cn_skewness  <- grep("^skewness_", colnames(tidy_train))
cn_max       <- grep("^max_",      colnames(tidy_train))
cn_min       <- grep("^min_",      colnames(tidy_train))
cn_var       <- grep("^var_",      colnames(tidy_train))
cn_avg       <- grep("^avg_",      colnames(tidy_train))
cn_stddev    <- grep("^stddev_",   colnames(tidy_train))
cn_total     <- grep("^total_",      colnames(tidy_train))
cn_amplitude <- grep("^amplitude_",colnames(tidy_train))

exclusions <- c(artifacts, cn_kurtosis, cn_skewness, cn_max, cn_min,
               cn_var, cn_avg, cn_stddev, cn_total,  cn_amplitude)
tidy_train = tidy_train[,-exclusions]
dim(tidy_train)
colnames(tidy_train)
```



```{r echo=TRUE}
library(doMC)
registerDoMC(cores=2)

Sys.time()
library(caret)
library(randomForest)
set.seed(1018)
folds <- createFolds(y=tidy_train$classe,k=4,returnTrain=FALSE)

train_1 <- tidy_train[-folds[[1]],]
test_1  <- tidy_train[ folds[[1]],]
train_2 <- tidy_train[-folds[[2]],]
test_2  <- tidy_train[ folds[[2]],]
train_3 <- tidy_train[-folds[[3]],]
test_3  <- tidy_train[ folds[[3]],]
train_4 <- tidy_train[-folds[[4]],]
test_4  <- tidy_train[ folds[[4]],]

Sys.time()
model_rf_1 <- randomForest(classe ~ ., train_1, ntree=200, norm.votes=FALSE)
model_rf_1
prediction_rf_1 <- predict(model_rf_1,test_1)
confusionMatrix(prediction_rf_1,test_1$classe)
Sys.time()

Sys.time()
model_rf_2 <- randomForest(classe ~ ., train_2, ntree=200, norm.votes=FALSE)
model_rf_2
prediction_rf_2 <- predict(model_rf_2,test_2)
confusionMatrix(prediction_rf_2,test_2$classe)
Sys.time()

Sys.time()
model_rf_3 <- randomForest(classe ~ ., train_3, ntree=200, norm.votes=FALSE)
model_rf_3
prediction_rf_3 <- predict(model_rf_3,test_3)
confusionMatrix(prediction_rf_3,test_3$classe)
Sys.time()


Sys.time()
model_rf_4 <- randomForest(classe ~ ., train_4, ntree=200, norm.votes=FALSE)
model_rf_4
prediction_rf_4 <- predict(model_rf_4,test_4)
confusionMatrix(prediction_rf_4,test_4$classe)
Sys.time()

Sys.time()
model_rf <- randomForest(classe ~ ., tidy_train, ntree=200, norm.votes=FALSE)
model_rf
Sys.time()
```

```{r echo=TRUE}
answers <- predict(model_rf, pml_test)
pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}
pml_write_files(answers)
```
